/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DistrictStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DistrictStatusTests
    {
        // TODO uncomment below to declare an instance variable for DistrictStatus
        //private DistrictStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DistrictStatus
            //instance = new DistrictStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DistrictStatus
        /// </summary>
        [Test]
        public void DistrictStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DistrictStatus
            //Assert.IsInstanceOfType<DistrictStatus> (instance, "variable 'instance' is a DistrictStatus");
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LastSync'
        /// </summary>
        [Test]
        public void LastSyncTest()
        {
            // TODO unit test for the property 'LastSync'
        }
        /// <summary>
        /// Test the property 'LaunchDate'
        /// </summary>
        [Test]
        public void LaunchDateTest()
        {
            // TODO unit test for the property 'LaunchDate'
        }
        /// <summary>
        /// Test the property 'PauseEnd'
        /// </summary>
        [Test]
        public void PauseEndTest()
        {
            // TODO unit test for the property 'PauseEnd'
        }
        /// <summary>
        /// Test the property 'PauseStart'
        /// </summary>
        [Test]
        public void PauseStartTest()
        {
            // TODO unit test for the property 'PauseStart'
        }
        /// <summary>
        /// Test the property 'SisType'
        /// </summary>
        [Test]
        public void SisTypeTest()
        {
            // TODO unit test for the property 'SisType'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
