/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StudentContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StudentContactTests
    {
        // TODO uncomment below to declare an instance variable for StudentContact
        //private StudentContact instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StudentContact
            //instance = new StudentContact();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StudentContact
        /// </summary>
        [Test]
        public void StudentContactInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StudentContact
            //Assert.IsInstanceOfType<StudentContact> (instance, "variable 'instance' is a StudentContact");
        }

        /// <summary>
        /// Test the property 'District'
        /// </summary>
        [Test]
        public void DistrictTest()
        {
            // TODO unit test for the property 'District'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'PhoneType'
        /// </summary>
        [Test]
        public void PhoneTypeTest()
        {
            // TODO unit test for the property 'PhoneType'
        }
        /// <summary>
        /// Test the property 'Relationship'
        /// </summary>
        [Test]
        public void RelationshipTest()
        {
            // TODO unit test for the property 'Relationship'
        }
        /// <summary>
        /// Test the property 'SisId'
        /// </summary>
        [Test]
        public void SisIdTest()
        {
            // TODO unit test for the property 'SisId'
        }
        /// <summary>
        /// Test the property 'Student'
        /// </summary>
        [Test]
        public void StudentTest()
        {
            // TODO unit test for the property 'Student'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
