/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Clever.Client;
using Clever.Api;
using Clever.Model;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing DataApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DataApiTests
    {
        private DataApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DataApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DataApi
            //Assert.IsInstanceOfType(typeof(DataApi), instance, "instance is a DataApi");
        }

        
        /// <summary>
        /// Test GetContact
        /// </summary>
        [Test]
        public void GetContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetContact(id);
            //Assert.IsInstanceOf<ContactResponse> (response, "response is ContactResponse");
        }
        
        /// <summary>
        /// Test GetContacts
        /// </summary>
        [Test]
        public void GetContactsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetContacts(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<ContactsResponse> (response, "response is ContactsResponse");
        }
        
        /// <summary>
        /// Test GetContactsForStudent
        /// </summary>
        [Test]
        public void GetContactsForStudentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //var response = instance.GetContactsForStudent(id, limit);
            //Assert.IsInstanceOf<ContactsResponse> (response, "response is ContactsResponse");
        }
        
        /// <summary>
        /// Test GetCourse
        /// </summary>
        [Test]
        public void GetCourseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetCourse(id);
            //Assert.IsInstanceOf<CourseResponse> (response, "response is CourseResponse");
        }
        
        /// <summary>
        /// Test GetCourseForSection
        /// </summary>
        [Test]
        public void GetCourseForSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetCourseForSection(id);
            //Assert.IsInstanceOf<CourseResponse> (response, "response is CourseResponse");
        }
        
        /// <summary>
        /// Test GetCourses
        /// </summary>
        [Test]
        public void GetCoursesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetCourses(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<CoursesResponse> (response, "response is CoursesResponse");
        }
        
        /// <summary>
        /// Test GetDistrict
        /// </summary>
        [Test]
        public void GetDistrictTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrict(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictAdmin
        /// </summary>
        [Test]
        public void GetDistrictAdminTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictAdmin(id);
            //Assert.IsInstanceOf<DistrictAdminResponse> (response, "response is DistrictAdminResponse");
        }
        
        /// <summary>
        /// Test GetDistrictAdmins
        /// </summary>
        [Test]
        public void GetDistrictAdminsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetDistrictAdmins(startingAfter, endingBefore);
            //Assert.IsInstanceOf<DistrictAdminsResponse> (response, "response is DistrictAdminsResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForContact
        /// </summary>
        [Test]
        public void GetDistrictForContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForContact(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForCourse
        /// </summary>
        [Test]
        public void GetDistrictForCourseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForCourse(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForDistrictAdmin
        /// </summary>
        [Test]
        public void GetDistrictForDistrictAdminTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForDistrictAdmin(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForSchool
        /// </summary>
        [Test]
        public void GetDistrictForSchoolTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForSchool(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForSchoolAdmin
        /// </summary>
        [Test]
        public void GetDistrictForSchoolAdminTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForSchoolAdmin(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForSection
        /// </summary>
        [Test]
        public void GetDistrictForSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForSection(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForStudent
        /// </summary>
        [Test]
        public void GetDistrictForStudentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForStudent(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForTeacher
        /// </summary>
        [Test]
        public void GetDistrictForTeacherTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForTeacher(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistrictForTerm
        /// </summary>
        [Test]
        public void GetDistrictForTermTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDistrictForTerm(id);
            //Assert.IsInstanceOf<DistrictResponse> (response, "response is DistrictResponse");
        }
        
        /// <summary>
        /// Test GetDistricts
        /// </summary>
        [Test]
        public void GetDistrictsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetDistricts();
            //Assert.IsInstanceOf<DistrictsResponse> (response, "response is DistrictsResponse");
        }
        
        /// <summary>
        /// Test GetSchool
        /// </summary>
        [Test]
        public void GetSchoolTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetSchool(id);
            //Assert.IsInstanceOf<SchoolResponse> (response, "response is SchoolResponse");
        }
        
        /// <summary>
        /// Test GetSchoolAdmin
        /// </summary>
        [Test]
        public void GetSchoolAdminTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetSchoolAdmin(id);
            //Assert.IsInstanceOf<SchoolAdminResponse> (response, "response is SchoolAdminResponse");
        }
        
        /// <summary>
        /// Test GetSchoolAdmins
        /// </summary>
        [Test]
        public void GetSchoolAdminsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSchoolAdmins(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SchoolAdminsResponse> (response, "response is SchoolAdminsResponse");
        }
        
        /// <summary>
        /// Test GetSchoolForSection
        /// </summary>
        [Test]
        public void GetSchoolForSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetSchoolForSection(id);
            //Assert.IsInstanceOf<SchoolResponse> (response, "response is SchoolResponse");
        }
        
        /// <summary>
        /// Test GetSchoolForStudent
        /// </summary>
        [Test]
        public void GetSchoolForStudentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetSchoolForStudent(id);
            //Assert.IsInstanceOf<SchoolResponse> (response, "response is SchoolResponse");
        }
        
        /// <summary>
        /// Test GetSchoolForTeacher
        /// </summary>
        [Test]
        public void GetSchoolForTeacherTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetSchoolForTeacher(id);
            //Assert.IsInstanceOf<SchoolResponse> (response, "response is SchoolResponse");
        }
        
        /// <summary>
        /// Test GetSchools
        /// </summary>
        [Test]
        public void GetSchoolsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSchools(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SchoolsResponse> (response, "response is SchoolsResponse");
        }
        
        /// <summary>
        /// Test GetSchoolsForSchoolAdmin
        /// </summary>
        [Test]
        public void GetSchoolsForSchoolAdminTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSchoolsForSchoolAdmin(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SchoolsResponse> (response, "response is SchoolsResponse");
        }
        
        /// <summary>
        /// Test GetSchoolsForStudent
        /// </summary>
        [Test]
        public void GetSchoolsForStudentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSchoolsForStudent(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SchoolsResponse> (response, "response is SchoolsResponse");
        }
        
        /// <summary>
        /// Test GetSchoolsForTeacher
        /// </summary>
        [Test]
        public void GetSchoolsForTeacherTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSchoolsForTeacher(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SchoolsResponse> (response, "response is SchoolsResponse");
        }
        
        /// <summary>
        /// Test GetSection
        /// </summary>
        [Test]
        public void GetSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetSection(id);
            //Assert.IsInstanceOf<SectionResponse> (response, "response is SectionResponse");
        }
        
        /// <summary>
        /// Test GetSections
        /// </summary>
        [Test]
        public void GetSectionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSections(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SectionsResponse> (response, "response is SectionsResponse");
        }
        
        /// <summary>
        /// Test GetSectionsForCourse
        /// </summary>
        [Test]
        public void GetSectionsForCourseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSectionsForCourse(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SectionsResponse> (response, "response is SectionsResponse");
        }
        
        /// <summary>
        /// Test GetSectionsForSchool
        /// </summary>
        [Test]
        public void GetSectionsForSchoolTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSectionsForSchool(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SectionsResponse> (response, "response is SectionsResponse");
        }
        
        /// <summary>
        /// Test GetSectionsForStudent
        /// </summary>
        [Test]
        public void GetSectionsForStudentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSectionsForStudent(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SectionsResponse> (response, "response is SectionsResponse");
        }
        
        /// <summary>
        /// Test GetSectionsForTeacher
        /// </summary>
        [Test]
        public void GetSectionsForTeacherTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSectionsForTeacher(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SectionsResponse> (response, "response is SectionsResponse");
        }
        
        /// <summary>
        /// Test GetSectionsForTerm
        /// </summary>
        [Test]
        public void GetSectionsForTermTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetSectionsForTerm(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<SectionsResponse> (response, "response is SectionsResponse");
        }
        
        /// <summary>
        /// Test GetStudent
        /// </summary>
        [Test]
        public void GetStudentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetStudent(id);
            //Assert.IsInstanceOf<StudentResponse> (response, "response is StudentResponse");
        }
        
        /// <summary>
        /// Test GetStudents
        /// </summary>
        [Test]
        public void GetStudentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetStudents(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<StudentsResponse> (response, "response is StudentsResponse");
        }
        
        /// <summary>
        /// Test GetStudentsForContact
        /// </summary>
        [Test]
        public void GetStudentsForContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetStudentsForContact(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<StudentsResponse> (response, "response is StudentsResponse");
        }
        
        /// <summary>
        /// Test GetStudentsForSchool
        /// </summary>
        [Test]
        public void GetStudentsForSchoolTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetStudentsForSchool(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<StudentsResponse> (response, "response is StudentsResponse");
        }
        
        /// <summary>
        /// Test GetStudentsForSection
        /// </summary>
        [Test]
        public void GetStudentsForSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetStudentsForSection(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<StudentsResponse> (response, "response is StudentsResponse");
        }
        
        /// <summary>
        /// Test GetStudentsForTeacher
        /// </summary>
        [Test]
        public void GetStudentsForTeacherTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetStudentsForTeacher(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<StudentsResponse> (response, "response is StudentsResponse");
        }
        
        /// <summary>
        /// Test GetTeacher
        /// </summary>
        [Test]
        public void GetTeacherTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetTeacher(id);
            //Assert.IsInstanceOf<TeacherResponse> (response, "response is TeacherResponse");
        }
        
        /// <summary>
        /// Test GetTeacherForSection
        /// </summary>
        [Test]
        public void GetTeacherForSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetTeacherForSection(id);
            //Assert.IsInstanceOf<TeacherResponse> (response, "response is TeacherResponse");
        }
        
        /// <summary>
        /// Test GetTeachers
        /// </summary>
        [Test]
        public void GetTeachersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetTeachers(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<TeachersResponse> (response, "response is TeachersResponse");
        }
        
        /// <summary>
        /// Test GetTeachersForSchool
        /// </summary>
        [Test]
        public void GetTeachersForSchoolTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetTeachersForSchool(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<TeachersResponse> (response, "response is TeachersResponse");
        }
        
        /// <summary>
        /// Test GetTeachersForSection
        /// </summary>
        [Test]
        public void GetTeachersForSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetTeachersForSection(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<TeachersResponse> (response, "response is TeachersResponse");
        }
        
        /// <summary>
        /// Test GetTeachersForStudent
        /// </summary>
        [Test]
        public void GetTeachersForStudentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetTeachersForStudent(id, limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<TeachersResponse> (response, "response is TeachersResponse");
        }
        
        /// <summary>
        /// Test GetTerm
        /// </summary>
        [Test]
        public void GetTermTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetTerm(id);
            //Assert.IsInstanceOf<TermResponse> (response, "response is TermResponse");
        }
        
        /// <summary>
        /// Test GetTermForSection
        /// </summary>
        [Test]
        public void GetTermForSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetTermForSection(id);
            //Assert.IsInstanceOf<TermResponse> (response, "response is TermResponse");
        }
        
        /// <summary>
        /// Test GetTerms
        /// </summary>
        [Test]
        public void GetTermsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string startingAfter = null;
            //string endingBefore = null;
            //var response = instance.GetTerms(limit, startingAfter, endingBefore);
            //Assert.IsInstanceOf<TermsResponse> (response, "response is TermsResponse");
        }
        
    }

}
