version: 2
jobs:
  build:
    working_directory: ~/Clever/clever-csharp
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run:
       command: |-
         sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
         echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
         sudo apt-get update
         sudo apt-get install mono-devel
         make build
       name: make build
    - run: TERM=xterm-256color make test
    - run:
        command: |-
          cd /tmp/ && wget https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
          sudo apt-get update
          sudo apt-get install python-dev
          sudo pip install --upgrade awscli && aws --version
          pip install --upgrade --user awscli
        name: Install awscli for ECR publish
