# Copy autogenerated files into Clever directory and rename
mv IO.Swagger.sln Clever.sln || true
cp -R src/IO.Swagger/. src/Clever || true
mv src/Clever/IO.Swagger.csproj src/Clever/Clever.csproj || true
mv src/Clever/IO.Swagger.nuspec src/Clever/Clever.nuspec || true
cp -R src/IO.Swagger.Test/. src/Clever.Test || true
mv src/Clever.Test/IO.Swagger.Test.csproj src/Clever.Test/Clever.Test.csproj || true
rm -rf src/IO.Swagger || true
rm -rf src/IO.Swagger.Test || true

# Rename references of IO.Swagger to Clever
git grep -l 'IO.Swagger' -- './*' ':(exclude)override/override.sh' | xargs sed -i "" 's/IO.Swagger/Clever/g'

# Update the README
mv README.md docs/README.md
sed -i "" 's/<a name="documentation-for-api-endpoints">/<EOD>\'$'\n<a name="documentation-for-api-endpoints">/g' docs/README.md
sed -i "" '/<a name="packaging">/,/<EOD>/d' docs/README.md
cp override/README.md README.md

# Output instructions to update the API Client
echo ""
echo ""
echo "Now add the following line to the 3 constructors in src/Clever/Client/ApiClient.cs:"
echo "$(tput setaf 2)serializerSettings.Converters.Add(new CleverEventJsonConverter());$(tput sgr 0)"
