/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Clever.Client.SwaggerDateConverter;

namespace Clever.Model
{
    /// <summary>
    /// School
    /// </summary>
    [DataContract]
    public partial class School :  IEquatable<School>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets HighGrade
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum HighGradeEnum
        {
            
            /// <summary>
            /// Enum _1 for "1"
            /// </summary>
            [EnumMember(Value = "1")]
            _1,
            
            /// <summary>
            /// Enum _2 for "2"
            /// </summary>
            [EnumMember(Value = "2")]
            _2,
            
            /// <summary>
            /// Enum _3 for "3"
            /// </summary>
            [EnumMember(Value = "3")]
            _3,
            
            /// <summary>
            /// Enum _4 for "4"
            /// </summary>
            [EnumMember(Value = "4")]
            _4,
            
            /// <summary>
            /// Enum _5 for "5"
            /// </summary>
            [EnumMember(Value = "5")]
            _5,
            
            /// <summary>
            /// Enum _6 for "6"
            /// </summary>
            [EnumMember(Value = "6")]
            _6,
            
            /// <summary>
            /// Enum _7 for "7"
            /// </summary>
            [EnumMember(Value = "7")]
            _7,
            
            /// <summary>
            /// Enum _8 for "8"
            /// </summary>
            [EnumMember(Value = "8")]
            _8,
            
            /// <summary>
            /// Enum _9 for "9"
            /// </summary>
            [EnumMember(Value = "9")]
            _9,
            
            /// <summary>
            /// Enum _10 for "10"
            /// </summary>
            [EnumMember(Value = "10")]
            _10,
            
            /// <summary>
            /// Enum _11 for "11"
            /// </summary>
            [EnumMember(Value = "11")]
            _11,
            
            /// <summary>
            /// Enum _12 for "12"
            /// </summary>
            [EnumMember(Value = "12")]
            _12,
            
            /// <summary>
            /// Enum PreKindergarten for "PreKindergarten"
            /// </summary>
            [EnumMember(Value = "PreKindergarten")]
            PreKindergarten,
            
            /// <summary>
            /// Enum Kindergarten for "Kindergarten"
            /// </summary>
            [EnumMember(Value = "Kindergarten")]
            Kindergarten,
            
            /// <summary>
            /// Enum PostGraduate for "PostGraduate"
            /// </summary>
            [EnumMember(Value = "PostGraduate")]
            PostGraduate,
            
            /// <summary>
            /// Enum Other for "Other"
            /// </summary>
            [EnumMember(Value = "Other")]
            Other
        }

        /// <summary>
        /// Gets or Sets LowGrade
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LowGradeEnum
        {
            
            /// <summary>
            /// Enum _1 for "1"
            /// </summary>
            [EnumMember(Value = "1")]
            _1,
            
            /// <summary>
            /// Enum _2 for "2"
            /// </summary>
            [EnumMember(Value = "2")]
            _2,
            
            /// <summary>
            /// Enum _3 for "3"
            /// </summary>
            [EnumMember(Value = "3")]
            _3,
            
            /// <summary>
            /// Enum _4 for "4"
            /// </summary>
            [EnumMember(Value = "4")]
            _4,
            
            /// <summary>
            /// Enum _5 for "5"
            /// </summary>
            [EnumMember(Value = "5")]
            _5,
            
            /// <summary>
            /// Enum _6 for "6"
            /// </summary>
            [EnumMember(Value = "6")]
            _6,
            
            /// <summary>
            /// Enum _7 for "7"
            /// </summary>
            [EnumMember(Value = "7")]
            _7,
            
            /// <summary>
            /// Enum _8 for "8"
            /// </summary>
            [EnumMember(Value = "8")]
            _8,
            
            /// <summary>
            /// Enum _9 for "9"
            /// </summary>
            [EnumMember(Value = "9")]
            _9,
            
            /// <summary>
            /// Enum _10 for "10"
            /// </summary>
            [EnumMember(Value = "10")]
            _10,
            
            /// <summary>
            /// Enum _11 for "11"
            /// </summary>
            [EnumMember(Value = "11")]
            _11,
            
            /// <summary>
            /// Enum _12 for "12"
            /// </summary>
            [EnumMember(Value = "12")]
            _12,
            
            /// <summary>
            /// Enum PreKindergarten for "PreKindergarten"
            /// </summary>
            [EnumMember(Value = "PreKindergarten")]
            PreKindergarten,
            
            /// <summary>
            /// Enum Kindergarten for "Kindergarten"
            /// </summary>
            [EnumMember(Value = "Kindergarten")]
            Kindergarten,
            
            /// <summary>
            /// Enum PostGraduate for "PostGraduate"
            /// </summary>
            [EnumMember(Value = "PostGraduate")]
            PostGraduate,
            
            /// <summary>
            /// Enum Other for "Other"
            /// </summary>
            [EnumMember(Value = "Other")]
            Other
        }

        /// <summary>
        /// Gets or Sets HighGrade
        /// </summary>
        [DataMember(Name="high_grade", EmitDefaultValue=false)]
        public HighGradeEnum? HighGrade { get; set; }
        /// <summary>
        /// Gets or Sets LowGrade
        /// </summary>
        [DataMember(Name="low_grade", EmitDefaultValue=false)]
        public LowGradeEnum? LowGrade { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="School" /> class.
        /// </summary>
        /// <param name="Created">Created.</param>
        /// <param name="District">District.</param>
        /// <param name="HighGrade">HighGrade.</param>
        /// <param name="Id">Id.</param>
        /// <param name="LastModified">LastModified.</param>
        /// <param name="Location">Location.</param>
        /// <param name="LowGrade">LowGrade.</param>
        /// <param name="MdrNumber">MdrNumber.</param>
        /// <param name="Name">Name.</param>
        /// <param name="NcesId">NcesId.</param>
        /// <param name="Phone">Phone.</param>
        /// <param name="Principal">Principal.</param>
        /// <param name="SchoolNumber">SchoolNumber.</param>
        /// <param name="SisId">SisId.</param>
        /// <param name="StateId">StateId.</param>
        public School(string Created = default(string), string District = default(string), HighGradeEnum? HighGrade = default(HighGradeEnum?), string Id = default(string), string LastModified = default(string), Location Location = default(Location), LowGradeEnum? LowGrade = default(LowGradeEnum?), string MdrNumber = default(string), string Name = default(string), string NcesId = default(string), string Phone = default(string), Principal Principal = default(Principal), string SchoolNumber = default(string), string SisId = default(string), string StateId = default(string))
        {
            this.Created = Created;
            this.District = District;
            this.HighGrade = HighGrade;
            this.Id = Id;
            this.LastModified = LastModified;
            this.Location = Location;
            this.LowGrade = LowGrade;
            this.MdrNumber = MdrNumber;
            this.Name = Name;
            this.NcesId = NcesId;
            this.Phone = Phone;
            this.Principal = Principal;
            this.SchoolNumber = SchoolNumber;
            this.SisId = SisId;
            this.StateId = StateId;
        }
        
        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public string Created { get; set; }

        /// <summary>
        /// Gets or Sets District
        /// </summary>
        [DataMember(Name="district", EmitDefaultValue=false)]
        public string District { get; set; }


        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name="last_modified", EmitDefaultValue=false)]
        public string LastModified { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public Location Location { get; set; }


        /// <summary>
        /// Gets or Sets MdrNumber
        /// </summary>
        [DataMember(Name="mdr_number", EmitDefaultValue=false)]
        public string MdrNumber { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets NcesId
        /// </summary>
        [DataMember(Name="nces_id", EmitDefaultValue=false)]
        public string NcesId { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [DataMember(Name="phone", EmitDefaultValue=false)]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or Sets Principal
        /// </summary>
        [DataMember(Name="principal", EmitDefaultValue=false)]
        public Principal Principal { get; set; }

        /// <summary>
        /// Gets or Sets SchoolNumber
        /// </summary>
        [DataMember(Name="school_number", EmitDefaultValue=false)]
        public string SchoolNumber { get; set; }

        /// <summary>
        /// Gets or Sets SisId
        /// </summary>
        [DataMember(Name="sis_id", EmitDefaultValue=false)]
        public string SisId { get; set; }

        /// <summary>
        /// Gets or Sets StateId
        /// </summary>
        [DataMember(Name="state_id", EmitDefaultValue=false)]
        public string StateId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class School {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  District: ").Append(District).Append("\n");
            sb.Append("  HighGrade: ").Append(HighGrade).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  LowGrade: ").Append(LowGrade).Append("\n");
            sb.Append("  MdrNumber: ").Append(MdrNumber).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NcesId: ").Append(NcesId).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Principal: ").Append(Principal).Append("\n");
            sb.Append("  SchoolNumber: ").Append(SchoolNumber).Append("\n");
            sb.Append("  SisId: ").Append(SisId).Append("\n");
            sb.Append("  StateId: ").Append(StateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as School);
        }

        /// <summary>
        /// Returns true if School instances are equal
        /// </summary>
        /// <param name="input">Instance of School to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(School input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.District == input.District ||
                    (this.District != null &&
                    this.District.Equals(input.District))
                ) && 
                (
                    this.HighGrade == input.HighGrade ||
                    (this.HighGrade != null &&
                    this.HighGrade.Equals(input.HighGrade))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.LastModified == input.LastModified ||
                    (this.LastModified != null &&
                    this.LastModified.Equals(input.LastModified))
                ) && 
                (
                    this.Location == input.Location ||
                    (this.Location != null &&
                    this.Location.Equals(input.Location))
                ) && 
                (
                    this.LowGrade == input.LowGrade ||
                    (this.LowGrade != null &&
                    this.LowGrade.Equals(input.LowGrade))
                ) && 
                (
                    this.MdrNumber == input.MdrNumber ||
                    (this.MdrNumber != null &&
                    this.MdrNumber.Equals(input.MdrNumber))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.NcesId == input.NcesId ||
                    (this.NcesId != null &&
                    this.NcesId.Equals(input.NcesId))
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                ) && 
                (
                    this.Principal == input.Principal ||
                    (this.Principal != null &&
                    this.Principal.Equals(input.Principal))
                ) && 
                (
                    this.SchoolNumber == input.SchoolNumber ||
                    (this.SchoolNumber != null &&
                    this.SchoolNumber.Equals(input.SchoolNumber))
                ) && 
                (
                    this.SisId == input.SisId ||
                    (this.SisId != null &&
                    this.SisId.Equals(input.SisId))
                ) && 
                (
                    this.StateId == input.StateId ||
                    (this.StateId != null &&
                    this.StateId.Equals(input.StateId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                if (this.District != null)
                    hashCode = hashCode * 59 + this.District.GetHashCode();
                if (this.HighGrade != null)
                    hashCode = hashCode * 59 + this.HighGrade.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.LastModified != null)
                    hashCode = hashCode * 59 + this.LastModified.GetHashCode();
                if (this.Location != null)
                    hashCode = hashCode * 59 + this.Location.GetHashCode();
                if (this.LowGrade != null)
                    hashCode = hashCode * 59 + this.LowGrade.GetHashCode();
                if (this.MdrNumber != null)
                    hashCode = hashCode * 59 + this.MdrNumber.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.NcesId != null)
                    hashCode = hashCode * 59 + this.NcesId.GetHashCode();
                if (this.Phone != null)
                    hashCode = hashCode * 59 + this.Phone.GetHashCode();
                if (this.Principal != null)
                    hashCode = hashCode * 59 + this.Principal.GetHashCode();
                if (this.SchoolNumber != null)
                    hashCode = hashCode * 59 + this.SchoolNumber.GetHashCode();
                if (this.SisId != null)
                    hashCode = hashCode * 59 + this.SisId.GetHashCode();
                if (this.StateId != null)
                    hashCode = hashCode * 59 + this.StateId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
