/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing DistrictadminsCreated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DistrictadminsCreatedTests
    {
        // TODO uncomment below to declare an instance variable for DistrictadminsCreated
        //private DistrictadminsCreated instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DistrictadminsCreated
            //instance = new DistrictadminsCreated();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DistrictadminsCreated
        /// </summary>
        [Test]
        public void DistrictadminsCreatedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DistrictadminsCreated
            //Assert.IsInstanceOfType<DistrictadminsCreated> (instance, "variable 'instance' is a DistrictadminsCreated");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
