/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing School
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SchoolTests
    {
        // TODO uncomment below to declare an instance variable for School
        //private School instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of School
            //instance = new School();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of School
        /// </summary>
        [Test]
        public void SchoolInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" School
            //Assert.IsInstanceOfType<School> (instance, "variable 'instance' is a School");
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'District'
        /// </summary>
        [Test]
        public void DistrictTest()
        {
            // TODO unit test for the property 'District'
        }
        /// <summary>
        /// Test the property 'HighGrade'
        /// </summary>
        [Test]
        public void HighGradeTest()
        {
            // TODO unit test for the property 'HighGrade'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'LowGrade'
        /// </summary>
        [Test]
        public void LowGradeTest()
        {
            // TODO unit test for the property 'LowGrade'
        }
        /// <summary>
        /// Test the property 'MdrNumber'
        /// </summary>
        [Test]
        public void MdrNumberTest()
        {
            // TODO unit test for the property 'MdrNumber'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NcesId'
        /// </summary>
        [Test]
        public void NcesIdTest()
        {
            // TODO unit test for the property 'NcesId'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Principal'
        /// </summary>
        [Test]
        public void PrincipalTest()
        {
            // TODO unit test for the property 'Principal'
        }
        /// <summary>
        /// Test the property 'SchoolNumber'
        /// </summary>
        [Test]
        public void SchoolNumberTest()
        {
            // TODO unit test for the property 'SchoolNumber'
        }
        /// <summary>
        /// Test the property 'SisId'
        /// </summary>
        [Test]
        public void SisIdTest()
        {
            // TODO unit test for the property 'SisId'
        }
        /// <summary>
        /// Test the property 'StateId'
        /// </summary>
        [Test]
        public void StateIdTest()
        {
            // TODO unit test for the property 'StateId'
        }

    }

}
