/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing StudentObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StudentObjectTests
    {
        // TODO uncomment below to declare an instance variable for StudentObject
        //private StudentObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StudentObject
            //instance = new StudentObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StudentObject
        /// </summary>
        [Test]
        public void StudentObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StudentObject
            //Assert.IsInstanceOfType<StudentObject> (instance, "variable 'instance' is a StudentObject");
        }


        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }

    }

}
