/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing StudentContactObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StudentContactObjectTests
    {
        // TODO uncomment below to declare an instance variable for StudentContactObject
        //private StudentContactObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StudentContactObject
            //instance = new StudentContactObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StudentContactObject
        /// </summary>
        [Test]
        public void StudentContactObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StudentContactObject
            //Assert.IsInstanceOfType<StudentContactObject> (instance, "variable 'instance' is a StudentContactObject");
        }

        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }

    }

}
