/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing Student
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StudentTests
    {
        // TODO uncomment below to declare an instance variable for Student
        //private Student instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Student
            //instance = new Student();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Student
        /// </summary>
        [Test]
        public void StudentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Student
            //Assert.IsInstanceOfType<Student> (instance, "variable 'instance' is a Student");
        }


        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Test]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'District'
        /// </summary>
        [Test]
        public void DistrictTest()
        {
            // TODO unit test for the property 'District'
        }
        /// <summary>
        /// Test the property 'Dob'
        /// </summary>
        [Test]
        public void DobTest()
        {
            // TODO unit test for the property 'Dob'
        }
        /// <summary>
        /// Test the property 'EllStatus'
        /// </summary>
        [Test]
        public void EllStatusTest()
        {
            // TODO unit test for the property 'EllStatus'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'Grade'
        /// </summary>
        [Test]
        public void GradeTest()
        {
            // TODO unit test for the property 'Grade'
        }
        /// <summary>
        /// Test the property 'GraduationYear'
        /// </summary>
        [Test]
        public void GraduationYearTest()
        {
            // TODO unit test for the property 'GraduationYear'
        }
        /// <summary>
        /// Test the property 'HispanicEthnicity'
        /// </summary>
        [Test]
        public void HispanicEthnicityTest()
        {
            // TODO unit test for the property 'HispanicEthnicity'
        }
        /// <summary>
        /// Test the property 'HomeLanguage'
        /// </summary>
        [Test]
        public void HomeLanguageTest()
        {
            // TODO unit test for the property 'HomeLanguage'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IepStatus'
        /// </summary>
        [Test]
        public void IepStatusTest()
        {
            // TODO unit test for the property 'IepStatus'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Race'
        /// </summary>
        [Test]
        public void RaceTest()
        {
            // TODO unit test for the property 'Race'
        }
        /// <summary>
        /// Test the property 'School'
        /// </summary>
        [Test]
        public void SchoolTest()
        {
            // TODO unit test for the property 'School'
        }
        /// <summary>
        /// Test the property 'Schools'
        /// </summary>
        [Test]
        public void SchoolsTest()
        {
            // TODO unit test for the property 'Schools'
        }
        /// <summary>
        /// Test the property 'SisId'
        /// </summary>
        [Test]
        public void SisIdTest()
        {
            // TODO unit test for the property 'SisId'
        }
        /// <summary>
        /// Test the property 'StateId'
        /// </summary>
        [Test]
        public void StateIdTest()
        {
            // TODO unit test for the property 'StateId'
        }
        /// <summary>
        /// Test the property 'StudentNumber'
        /// </summary>
        [Test]
        public void StudentNumberTest()
        {
            // TODO unit test for the property 'StudentNumber'
        }
        /// <summary>
        /// Test the property 'UnweightedGpa'
        /// </summary>
        [Test]
        public void UnweightedGpaTest()
        {
            // TODO unit test for the property 'UnweightedGpa'
        }
        /// <summary>
        /// Test the property 'WeightedGpa'
        /// </summary>
        [Test]
        public void WeightedGpaTest()
        {
            // TODO unit test for the property 'WeightedGpa'
        }

    }

}
