/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Clever.Api;
using Clever.Model;
using Clever.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Clever.Test
{
    /// <summary>
    ///  Class for testing Teacher
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeacherTests
    {
        // TODO uncomment below to declare an instance variable for Teacher
        //private Teacher instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Teacher
            //instance = new Teacher();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Teacher
        /// </summary>
        [Test]
        public void TeacherInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Teacher
            //Assert.IsInstanceOfType<Teacher> (instance, "variable 'instance' is a Teacher");
        }


        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Test]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'District'
        /// </summary>
        [Test]
        public void DistrictTest()
        {
            // TODO unit test for the property 'District'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'School'
        /// </summary>
        [Test]
        public void SchoolTest()
        {
            // TODO unit test for the property 'School'
        }
        /// <summary>
        /// Test the property 'Schools'
        /// </summary>
        [Test]
        public void SchoolsTest()
        {
            // TODO unit test for the property 'Schools'
        }
        /// <summary>
        /// Test the property 'SisId'
        /// </summary>
        [Test]
        public void SisIdTest()
        {
            // TODO unit test for the property 'SisId'
        }
        /// <summary>
        /// Test the property 'StateId'
        /// </summary>
        [Test]
        public void StateIdTest()
        {
            // TODO unit test for the property 'StateId'
        }
        /// <summary>
        /// Test the property 'TeacherNumber'
        /// </summary>
        [Test]
        public void TeacherNumberTest()
        {
            // TODO unit test for the property 'TeacherNumber'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
